### PR TITLE
Enable msvc

### PR DESCRIPTION
**Pull request by tkralphs**
Here is a patch that adds an argument ```--enable-msvc``` to your configure script. I tested it and I think it works fine on both Windows and non-Windows systems. I have to admit, though, that I am not exactly an autoconf ninja and I was a little confused by what you already had in your ```configure.ac```. You had calls to ```AC_PROG_CXX``` and ```AC_PROG_CC``` in configure.ac already, but they seemed to come after autoconf had already inserted its own automatic call, so it looked like they would not have any effect. To have the modified search order take effect, I had to move the whole thing to almost the very top of the script. 

I'm also not a git ninja. I'm sorry that this pull request consists of so many changes when all I really want is to show you the change to configure.ac. The rest is superfluous, since you will re-run autoconf to produce the other files. I could probably figure out how to squash these commits, but the diff to configure.ac is just [this](https://github.com/tkralphs/CppAD/compare/coin-or:master...enable-msvc#diff-67e997bcfdac55191033d57a16d1408a). I would say you should just take that diff and apply it locally rather than accepting this merge request. 

There are probably some things about your configure setup that I'm missing, but this is at least a starting point if you want to add this functionality, which would be most appreciated. I just remembered that you wanted this to be undocumented and I made it documented, but I suppose you can easily delete the help when you apply the patch.

### CODE REVIEW

**Comment by tkralphs** [comment]
Unfortunately, your first cut doesn't work. Moving the call to ```AC_PROG_CXX``` call even down as far as you did renders it ineffective. If it doesn't come immediately after the check for pkg-config, then gcc is chosen automatically. The problem seems to have to do with the check for ```ar```. Apparently checking for ```ar``` requires a compiler and so one is chosen from the default list before the later call to ```AC_PROG_CXX```, which means gcc is always chosen. I guess you can either move the check for ```ar``` down or the definition of enable-msvc up.

I take your point about ```--enable-feature```. Actually, for compiled projects ```--enable-msvc``` takes an argument which tells it which run-time library to use, which is more in the spirit of things. In any case, it is a bit too late to change it now, so I am OK with it. It is mostly used by developers.

This does bring up one fix that is need, though. The check for for the value of ```enable_msvc``` should be
```if test $enable_msvc != no```
rather than
```if test $enable_msvc = yes```
in case it takes an optional value.

**Comment by bradbell** [comment]
On 2/15/2015 9:42 AM, Ted Ralphs wrote:
>
> Unfortunately, your first cut doesn't work. Moving the call to 
> |AC_PROG_CXX| call even down as far as you did renders it ineffective. 
> If it doesn't come immediately after the check for pkg-config, then 
> gcc is chosen automatically. The problem seems to have to do with the 
> check for |ar|. Apparently checking for |ar| requires a compiler and 
> so one is chosen from the default list before the later call to 
> |AC_PROG_CXX|, which means gcc is always chosen. I guess you can 
> either move the check for |ar| down or the definition of enable-msvc up.
>
> I take your point about |--enable-feature|. Actually, for compiled 
> projects |--enable-msvc| takes an argument which tells it which 
> run-time library to use, which is more in the spirit of things. In any 
> case, it is a bit too late to change it now, so I am OK with it. It is 
> mostly used by developers.
>
> This does bring up one fix that is need, though. The check for for the 
> value of |enable_msvc| should be
> |if test $enable_msvc != no|
> rather than
> |if test $enable_msvc = yes|
> in case it takes an optional value.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/coin-or/CppAD/pull/6#issuecomment-74424823>.
>
Moving the check for AR (and pkconfig) below the setting of AC_PROG_CXX 
and AC_PROG_CC produces the message
     configure: WARNING: compilation failed
     configure: error: conditional "AMDEP" was never defined.
     Usually this means the macro was only invoked conditionally.
Looking at
http://stackoverflow.com/questions/10629071/error-message-amdep-was-never-defined
it appears that AC_PROG_CXX and AC_PROG_CC cannot be inside an if block.

**Comment by tkralphs** [comment]
cd build

**Comment by tkralphs** [comment]
I don't really understand why that erorr would arise as long as ```AC_PROG_CXX``` is called in both branches of the if statement. Something like this seems to work, though:
```
if  test "$enable_msvc" != no; then
	dnl This case is defined and supported by Ted Ralphs
	comps="cl icl g++"
else
	comps=
fi
AC_PROG_CXX([$comps])
```
What's weird is that making that change for ```AC_PROG_CXX``` is enough to get rid of the error. I can then have a conditional call for ```AC_PROG_CC``` and I get no complaint. I guess only one of the two needs to be called to make it happy.

I noticed that you commented out the check for the Fortran compiler. I initially didn't think that would be necessary either, but with that commented out, it is still searching for a Fortran compiler (and this was happening before I added this call as well, which is why I added it). I'm not sure why it looks for a Fortran compiler, since, as you say, CppAD has no Fortran code. Some test you are doing must require Fortran (just as the test for ```ar``` required a C compiler). On CYGWIN, it therefore finds ```gfortran``` rather than ```ifort```, which is the compiler we may really using if ```--enable-msvc``` is specified. I guess this will not cause any problems right now, but somewhere down the road, it could. I think it's better to have everything matching up as expected.

**Comment by bradbell** [comment]
I found a similar sequence that seems to work (the auto-tools are 
mysterious):
     if  test "$enable_msvc" = no; then
         AC_PROG_CC
     else
         dnl This case is defined and supported by Ted Ralphs
         AC_PROG_CC([cl icl gcc])
     fi
If I check for yes, and reverse to AC_PROG_CC commands, it seems to fail.

I am running my tests now and will try pushing if they succeed (there 
may be some delay due to my being out for a few hours).

P.S.
I am running with the check for the Fortran compiler as you suggested; i.e.
     if  test "$enable_msvc" != no; then
         dnl This case is defined and support by Ted Ralphs
         AC_PROG_F77([ifort gfortran])
     fi

**Comment by bradbell** [comment]
I have pushed another attempt to Github
https://github.com/coin-or/CppAD/commit/a0be36211e02f7854a7a9349fb6fed6107d9b12d

Please see if this works for you.

**Comment by tkralphs** [comment]
The call to ```AC_FC_LIBRARY_LDFLAGS``` still looks for gfortran libraries. I'm not sure what that command is needed for, but it is the reason the configure script was looking for the fortran compiler before I added my call to ```AC_PROG_F77```. I guess that I didn't notice this didn't entirely fix things up. 

Apparently, there are two Fortran compiler types that you can set, F77 and FC (modern Fortran). Adding a call to ```AC_PROG_FC``` fixes that problem.

But I am still getting the AMDEP error when I configure with ```--enable-msvc```. Switching the order didn't fix it. Even just changing it to
```
if  test "$enable_msvc" != no; then
	AC_PROG_CXX([cl icl g++])
fi
```
didn't fix things. I think we need to go with the other solution. That is the way it's done in [coin.m4](https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L310).

Here is the output from what you have checked in if it helps. This is all a lot to read on github than in e-mail.
```
checking for cl... cl
checking whether we are using the GNU C++ compiler... no
checking whether cl accepts -g... no
checking dependency style of cl... none
checking whether using Microsoft C++ compiler... yes
checking for cl... cl
checking whether we are using the GNU C compiler... no
checking whether cl accepts -g... no
checking for cl option to accept ISO C89... unsupported
checking dependency style of cl... none
checking for ifort... ifort
checking whether we are using the GNU Fortran 77 compiler... no
checking whether ifort accepts -g... no
checking for ar... ar
checking the archiver (ar) interface... ar
checking for pkg-config... yes
checking how to run the C preprocessor... cl -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... no
checking for sys/types.h... no
checking for sys/stat.h... no
checking for stdlib.h... no
checking for string.h... no
checking for memory.h... no
checking for strings.h... no
checking for inttypes.h... no
checking for stdint.h... no
checking for unistd.h... no
checking size of size_t... 4
checking size of unsigned int... 4
checking for gettimeofday... no
checking for ranlib... ranlib
checking how to run the C preprocessor... cl -E
checking for inline... no
checking for gfortran... gfortran
checking whether we are using the GNU Fortran compiler... no
checking whether gfortran accepts -g... no
checking build system type... x86_64-unknown-cygwin
checking host system type... x86_64-unknown-cygwin
checking how to get verbose linking output from gfortran... configure: WARNING: compilation failed

checking for Fortran libraries of gfortran...
checking for pthread_barrier_wait in -lpthread... no
checking for dlopen in -ldl... no
boost::thread library... no
checking for ddot in -lblas... yes
checking for dgesv in -llapack... yes
cppad_ipopt_nlp libraries: -L /lib -lipopt -lblas -llapack
checking that generated files are newer than configure... done
configure: error: conditional "AMDEP" was never defined.
Usually this means the macro was only invoked conditionally.
```

**Comment by bradbell** [comment]
All I am doing is moving the logic you had at the top to just below the 
setting of the variables corresponding to command line arguments. I do 
not want to change the configure.ac in a way that I do not understand; 
i.e., some global variable is being set and changing the effect in a way 
that I do not understand.

I wanted to use logic like
     if test "$enable_msvc" = no; then
         compiler_search_list="$the_default_compiler_search_list"
     else
         compiler_search_list="cl icl g++"
     AC_PROG_CXX([$compiler_search_list])
but I do not know how to get the auto-tools to tell me what the default 
compiler-search-list is for the current system.

**Comment by bradbell** [comment]
The FCLIBS symbol defined by AC_FC_LIBRARY_LDFLAGS is in the following 
makefile.am files
     cppad_ipopt/example/makefile.am
     cppad_ipopt/speed/makefile.am
     cppad_ipopt/test/makefile.am
     example/ipopt_solve/makefile.am
     test_more/makefile.am
It is needed to test cppad_ipopt (a deprecated binary library that gets 
installed) in the case where pkgconfig is not present.
     http://www.coin-or.org/CppAD/Doc/cppad_ipopt_nlp.xml
It has been replaced by the include file library
     http://www.coin-or.org/CppAD/Doc/ipopt_solve.xml

I am not sure why it is in
     test_more/makefile.am
perhaps it can be removed.

**Comment by bradbell** [comment]
Is there someone who is willing to take over the CppAD configure.ac 
script ? Is so, I am willing to give it up.

**Comment by tkralphs** [comment]
Commenting out ```AC_FC_LIBRARY_LDFLAGS``` fixes the warning you reported and I don't see how that could be required, since Ipopt itself does not require a "modern" Fortran compiler. 

I guess the solution to your concern about not knowing the default list of compilers is just to define a search list explicitly in both cases, as ```coin.m4``` does. I can just cut and paste the list from ```coin.m4``` into both parts if you want.

I'm willing to maintain ```configure.ac``` for my own purposes (or maybe to get the OS guys to do it), but you have a lot of stuff that you are doing for testing and a lot of use cases other than the ones I'm interested in that I have no idea about. If you want to abandon ```configure.ac``` and make it into something that is there just to link to COIN projects (mainly OS), then that is OK with me I guess. I might actually just bring it into line with the configure scripts of all the other projects in that case and use the macros in ```coin.m4```, which would make maintenance a lot easier and obviate the need for any of what we are trying to do here. I've always thought that was something that might make sense. I'm already essentially maintaining the ```configure.ac``` files for most of the projects in CoinAll.

**Comment by bradbell** [comment]
On 2/16/2015 9:41 AM, Ted Ralphs wrote:
>
> Commenting out |AC_FC_LIBRARY_LDFLAGS| fixes the warning you reported 
> and I don't see how that could be required, since Ipopt itself does 
> not require a "modern" Fortran compiler.
>
It is just a question of building the CppAD test of cppad_ipopt (a 
deprecated library).  Only the test will be missing if the configure 
script cannot figure out how to link Fortran properly.

> I guess the solution to your concern about not knowing the default 
> list of compilers is just to define a search list explicitly in both 
> cases, as |coin.m4| does. I can just cut and paste the list from 
> |coin.m4| into both parts if you want.
>
Lets give this a try. I will use the coin.m4 list. I think that with 
this approach I can fix all the problems in a way I understand and 
continue to maintain the configure script. I looked for the list in
     https://projects.coin-or.org/BuildTools/browser/trunk/coin.m4
but did not find it. Would you please send it to me for all three; i.e., 
the C++, C, and fortran compilers.

... snip ...

**Comment by tkralphs** [comment]
There was a link directly to the line in ```coin.m4``` where ```AC_PROG_CXX``` is invoked in my previous comment (I found it by grepping for ```AC_PROG_CXX``` in ```coin.m4```). Here are direct links to where the search lists are constructed:
 * https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L291
 * https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L707
 * https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L1247

**Comment by bradbell** [comment]
On 2/16/2015 3:46 PM, Ted Ralphs wrote:
>
> There was a link directly to the line in |coin.m4| where |AC_PROG_CXX| 
> is invoked in my previous comment (I found it by grepping for 
> |AC_PROG_CXX| in |coin.m4|). Here are direct links to where the search 
> lists are constructed:
>
>   * https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L291
>   * https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L707
>   * https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L1247
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/coin-or/CppAD/pull/6#issuecomment-74584380>.
>
Where does the variable $build get set ?

**Comment by bradbell** [comment]
On 2/16/2015 3:46 PM, Ted Ralphs wrote:
>
> There was a link directly to the line in |coin.m4| where |AC_PROG_CXX| 
> is invoked in my previous comment (I found it by grepping for 
> |AC_PROG_CXX| in |coin.m4|). Here are direct links to where the search 
> lists are constructed:
>
>   * https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L291
>   * https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L707
>   * https://github.com/coin-or-tools/BuildTools/blob/stable/0.8/coin.m4#L1247
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/coin-or/CppAD/pull/6#issuecomment-74584380>.
>
I think I have it working; see
https://github.com/coin-or/CppAD/commit/f718b47d51b5dc9c05fdd3c7cf9ea43e9e200a4b

I ran the configure in cygwin and did not get any warnings or errors.

In addition, I ran the
     https://github.com/coin-or/CppAD/blob/master/bin/jenkins.sh
test on the coin-jenkins system and it all worked. Note that it uses the 
configure script); see
     http://jenkins.coin-or.org:8080/job/cppad_trunk/523/console

You could use
      bin/jenkins.sh
this to run all the tests using the configure script on any system. It uses
     ./build
and
      ../build
for its work space. It will download a local copy of the optional 
packages so that all the tests get run.

**Comment by tkralphs** [comment]
It seems to work for me, but there's still some stuff I don't understand. With ifort, I get:
```
checking how to get verbose linking output from ifort... configure: WARNING: cannot determine how to obtain linking information from ifort

checking for Fortran libraries of ifort...
```
I guess that's not a problem, but I would like to run the full battery of tests. I looked at ```jenkins.sh but I am a bit afraid to run it because I don't know exactly what you meant by your statement that it uses ./build and ../build as work spaces. Relative to what? It seems a bit dangerous to use ../build if it's relative to the source root, which is where the ```jenkins.sh``` script must be run, since that would be a directory outside the source tree. Can you clarify? The script is sufficiently complex that I couldn't easily see the answer for myself.

**Comment by bradbell** [comment]
On 2/17/2015 1:22 PM, Ted Ralphs wrote:
... snip ...
> ||
>
> I looked at |jenkins.sh but I am a bit afraid to run it because I 
> don't know exactly what you meant by your statement that it uses 
> ./build and ../build as work spaces. Relative to what? It seems a bit 
> dangerous to use ../build if it's relative to the source root, which 
> is where the|jenkins.sh``` script must be run, since that would be a 
> directory outside the source tree. Can you clarify? The script is 
> sufficiently complex that I couldn't easily see the answer for myself.
>
If you look at the script that executes bin/jenkins.sh
     http://jenkins.coin-or.org:8080/job/cppad_trunk/configure
you will see it starts with
     cd trunk
so that in this case
     ../build
refers to the directory that the script starts in. I just wanted to warn 
you of this. This is done  because when I run on my own machine
     ./build
is used for the cmake build and
     ../build
is used for the auto-tools build. Perhaps
     ./builid/auto_tools
should be used for the auto-tools build. I will look into changing 
jenkins.sh in this way.

**Comment by bradbell** [comment]
Take a look at the following:
     http://ubuntuforums.org/archive/index.php/t-1232497.html
Perhaps there is an intel development library that needs to be installed ?

On 2/17/2015 1:22 PM, Ted Ralphs wrote:
>
> It seems to work for me, but there's still some stuff I don't 
> understand. With ifort, I get:
>
> |checking how to get verbose linking output from ifort... configure: WARNING: cannot determine how to obtain linking information from ifort
>
> checking for Fortran libraries of ifort...
> |
>
... snip ...

**Comment by bradbell** [comment]
The program
     bin/jenkins.sh
now uses build/auto_tools instead of ../build.sh. If you execute it 
without any arguments you will get a short description of how to use it. 
In addition, The commands under the heading Execute Shell on
     http://jenkins.coin-or.org:8080/job/cppad_trunk/configure
show how the jenkins system uses it and
     http://jenkins.coin-or.org:8080/job/cppad_trunk/525/console
is the console output from its last run on the jenkins system.

P.S.
You will have to change the configure command in bin/jenkins.sh if you 
are testing the --enable-msvc option.

**Comment by tkralphs** [comment]
Sorry for the delay. I tried running ```jenkins.sh``` on CYGWIN with CYGWIN CMake version 3.1 installed. The script fails because the out of 
```
cmake --version |  sed \
		-e 's|[^0-9]*|.|g ' \
		-e 's|\.\([0-9]*\)\.\([0-9]*\).*|\1 * 10 + \2|' \
	| bc
```
is 
```
31
31
31
```
when it is expected to be just ```31```. I am just going to test building CoinAll on all platforms with trunk and if that is OK, then we can call it a day.

**Comment by tkralphs** [comment]
It seems to work fine now on all platforms. Can you make a new release? Thanks!

**Comment by bradbell** [comment]
Please email me the files
     jenkins.log
     jenkins.err
so I can see what is going on (see more comments below)

On 2/20/2015 4:28 PM, Ted Ralphs wrote:
>
> Sorry for the delay. I tried running |jenkins.sh| on CYGWIN with 
> CYGWIN CMake version 3.1 installed. The script fails because the out of
>
> |cmake --version |  sed \
>          -e 's|[^0-9]*|.|g ' \
>          -e 's|\.\([0-9]*\)\.\([0-9]*\).*|\1 * 10 + \2|' \
>      | bc
> |
>
> is
>
> |31
> 31
> 31
> |
>
> when it is expected to be just |31|. I am just going to test building 
> CoinAll on all platforms with trunk and if that is OK, then we can 
> call it a day.
>
> Reply to this email directly or view it on GitHub 
> <https://github.com/coin-or/CppAD/pull/6#issuecomment-75338528>.
This is strange. There are only two places that the check for the 
version of cmake occurs. One is
     bin/get_sacado.sh
as
     if [ "$cmake_version" -ge '27' ]
     then
         cmake_program='cmake'
     else
     ...
The other is
     bin/get_eigen.sh
     if [ "$cmake_version" -ge '28' ]
     then
        cmake_program='cmake'
     else
     ...

**Comment by bradbell** [comment]
On 2/20/2015 5:54 PM, Ted Ralphs wrote:
>
> It seems to work fine now on all platforms. Can you make a new 
> release? Thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/coin-or/CppAD/pull/6#issuecomment-75346210>.
>
CppAD has a new releases at the beginning of every month; i.e., with 
versions of the form
     2015mm01
where mm is the month. These correspond to the trunk at the specified 
day and last until the next year when a new stable directory is created. 
While stable version have bug fixes, these first of the month releases 
do not.

For example; see
http://www.coin-or.org/download/source/CppAD/cppad-20150101.gpl.tgz
http://www.coin-or.org/download/source/CppAD/cppad-20150201.gpl.tgz

**Comment by tkralphs** [comment]
Yes, you are correct that the problem arises in those two scripts that you mentioned. Here is the contents of ```jenkins.err```:
```
bin/get_fadbad.sh
--2015-02-20 18:09:05--  http://www.fadbad.com/download/FADBAD++-2.1.tar.gz
Resolving www.fadbad.com (www.fadbad.com)... 194.126.234.133
Connecting to www.fadbad.com (www.fadbad.com)|194.126.234.133|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36623 (36K) [application/x-gzip]
Saving to: âFADBAD++-2.1.tar.gzâ

     0K .......... .......... .......... .....                100% 1.95M=0.02s

2015-02-20 18:09:05 (1.95 MB/s) - âFADBAD++-2.1.tar.gzâ saved [36623/36623]

bin/get_eigen.sh
bin/get_eigen.sh: line 80: [: 31
31
31: integer expression expected
```
I already debugged and found the problem is because of what I described above. 

I don't really understand what you're saying about your releases. If I go to 

https://projects.coin-or.org/CppAD/browser/releases

I see releases done in the stable series 2015000 that seem to be done in the standard way. There have been four this month including one that was cut because of the issue we're discussing. I was just asking you to cut release 20150000.9. Is that possible?

**Comment by bradbell** [comment]
The monthly releases are only in the tarball form, there is svn version 
of these releases.

**Comment by bradbell** [comment]
I see, you want a new 20150000 release that has the --enable-msvc option 
in it. There should only be bug fixes in each new release for a year. 
The 20150000.rel versions, should only support the features as of the 
documentation for the first of the year.

I will do as you suggest as a special exception (if you really want it 
and cannot just use the monthly tarballs instead).

Brad.

**Comment by bradbell** [comment]
I believe the following change will fix this problem:
https://github.com/coin-or/CppAD/commit/2e6c6d026df2f6a8089160e5994e7fdf47b28002
     https://projects.coin-or.org/CppAD/changeset/3657

Thanks.

**Comment by tkralphs** [comment]
> I see, you want a new 20150000 release that has the --enable-msvc option in it. There should only be bug fixes in each new release for a year. The 20150000.rel versions, should only support the features as of the documentation for the first of the year.

>I will do as you suggest as a special exception (if you really want it and cannot just use the monthly tarballs instead).

I do understand that it is atypical to add features between patch releases, but since this is a feature related to build only, since it is undocumented and does not effect previous use cases, and also fixes a "meta-bug" in compatibility between your build system and that of the rest of the COIN projects, I guess it is in a grey area. 

In any case, a special exception would be great. Unfortunately, I can't very easily use monthly tarballs, both because I don't want to wait for the next one to come out and because it would break our release scripts. We've got some special handling already to account for the fact that CppAD does not use semantic versioning and I'd prefer not to put additional exceptions in there. Thanks for looking into this and being so responsive. I really appreciate it!

**Comment by bradbell** [comment]
I copied the changes from the master to stable/20150000; see
     https://projects.coin-or.org/CppAD/changeset/3658
Please test
     stable/20150000
and see if it works for you. If so, I will create a new release 
corresponding to this version

**Comment by tkralphs** [comment]
Everything seems to work well with the stable version.

**Comment by bradbell** [comment]
A new release has been created (with the unspecified --enable-msvc 
option in the deprecated auto-tools install); see
     https://projects.coin-or.org/CppAD/browser/releases/20150000.9

**Comment by tkralphs** [comment]
OK, thanks!

**Pull request closed without merging**
