### PR TITLE
[OUTDATED] Fix the pkgconfig file generation

### LINKED ISSUE #62: Generated pkgconfig file not compliant with the standard
The `cppad.pc` file generated by the library does not contain the usual structure
```
prefix=${pcfiledir}/../..
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib
```
However, this creates several problems when I tried to import the library in `vcpkg` https://github.com/microsoft/vcpkg/pull/12560

Indeed as @Neumann-A suggested in https://github.com/microsoft/vcpkg/pull/12560#issuecomment-666373589 the `prefix` variable must be defined in every pkg-config file.

FYI @traversaro

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR fixes #62

### CODE REVIEW

**Comment by traversaro** [comment]
Hi @bradbell , if there is anything we can do to help the process of merging this PR, feel free to let us know, thanks!

**Comment by bradbell** [comment]
> This PR fixes #62

The title of #62 is:
``Generated pkgconfig file not compliant with the standard``
Where can I view the ``standard`` ?

I have been using the following documentation for pkgconfig:
https://people.freedesktop.org/~dbn/pkg-config-guide.html

It seems to say that the definitions at the top are just an example. In fact, exec_prefix is equal to prefix and there is no discussion of how it might be different. I can guess at the specifications for the other definitions: prefix, includedir, and libdir.

There is another issue here. I recently make use of Libs.private and Requires.private to get cppad_mixed.pc to work properly. I should be making use of them in the cppad.pc file.

**Comment by bradbell** [comment]
I am working on a new version of how pkg-config is used by cppad during the cmake command and need to better understand this pull request in terms of its requirements; i.e., example what is wrong with the current version of the cppad.pc file.

**Comment by traversaro** [comment]
Hi @bradbell, thanks for the reply. I was pinging the issue that @GiulioRomualdi (another member of my lab, as we both work in the same research institute opened). I think that @GiulioRomualdi assume that the `prefix` variable **must** be defined from this comment of @Neumann-A in https://github.com/microsoft/vcpkg/pull/12560#issuecomment-666373589 (for context, vcpkg is a C++ package manager, see https://docs.microsoft.com/en-us/cpp/build/vcpkg?view=msvc-160) : 
> Prefix must be defined. Patch the *.pc file if it is not defined in there. pkg-config does not work if the prefix is not defined (with a few exceptions). 

However, by inspecting the pkg-config documentation I also fail to find any reference to the fact that the `prefix` variable must by defined, so it is possible that @Neumann-A referred to a vcpkg-only constraint, in that case probably it make sense that the patch to fix this remains a vcpkg-specific patch and is not ported upstream.

**Comment by GiulioRomualdi** [comment]
Hi all, I'm not an expert of `pkgconfig` and I followed what @Neumann-A suggested in https://github.com/microsoft/vcpkg/pull/12560#issuecomment-666373589

**Comment by Neumann-A** [comment]
> However, by inspecting the pkg-config documentation I also fail to find any reference to the fact that the prefix variable must by defined,

`Since the variables are expanded recursively, this is very helpful when used in conjunction with autoconf derived paths.`

This means any used variable needs to be defined because otherwise the variable expansion will fail. There are some exception from the rules since on windows `prefix` gets redefined under some circumstances (e.g.  if the path ends in lib/pkgconfig and pkg-config has been build for windows) but otherwise all variables need to be defined. 
Looking at the `*.pc.in` file I see it is not using any commonly used variables and seems to encode everything using absolute paths? 
A `*.pc` file should at least use `prefix` as a variable since pkg-config has hardcoded features overwriting that variable (windows only: `--dont-define-prefix` `--prefix-variable=PREFIX`). By not using it you are basically breaking users expectation using the mentioned commands.

**Comment by traversaro** [comment]
Thanks @Neumann-A for chiming in!

**Comment by bradbell** [comment]
As I understand, vcpkg has some special requirements for the pkg-config files *.pc. There should be a place in the vcpkg documentation where theses requirements are specified. It not, perhaps you could list them on this issue page.

**Comment by bradbell** [comment]
I think I have the definitions I am looking for:
https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

**Comment by bradbell** [comment]
The newer version of cppad.pc,in 
https://github.com/coin-or/CppAD/blob/master/pkgconfig/cppad.pc.in
has the following definitions at the top:
```
prefix=@cppad_prefix@
exec_prefix=$(prefix)
includedir=${prefix}/@cppad_includedir@
libdir=${exec_prefix}/@cppad_libdir@
```
Does this fufill the requirements of this pull requrest ?

**Comment by GiulioRomualdi** [comment]
Hi @bradbell I tried to use the latest version of ` cppad.pc.in`, when I was trying to include `cppad/cppad.hpp` into my project I add the following error https://github.com/dic-iit/bipedal-locomotion-framework/issues/194

```
[ 66%] Building CXX object src/AutoDiff/tests/CMakeFiles/CppADTestUnitTests.dir/CppADTest.cpp.o
In file included from /home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/src/AutoDiff/tests/CppADTest.cpp:11:
/home/gromualdi/robot-code/robotology-superbuild/src/bipedal-locomotion-framework/src/AutoDiff/include/BipedalLocomotion/AutoDiff/CppAD.h:12:10: fatal error: cppad/cppad.hpp: No such file or directory
   12 | #include <cppad/cppad.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

So I investigated a bit and I noticed some typos in `cmake` machinery.
This patch completely fixes the problem.

Let me know if you are interested in a PR. (I can close this one and open a new one)  

```patch
diff --git a/pkgconfig/CMakeLists.txt b/pkgconfig/CMakeLists.txt
index 688087aa6..23f3ce880 100644
--- a/pkgconfig/CMakeLists.txt
+++ b/pkgconfig/CMakeLists.txt
@@ -122,7 +122,7 @@
 # and is set by cmake to the top soruce directory.
 #
 # cppad_includedir
-LIST(GET cmake_install_libdirs 0 cppad_includedir)
+LIST(GET cmake_install_includedirs 0 cppad_includedir)
 #
 # cppad_libdir
 LIST(GET cmake_install_libdirs 0 cppad_libdir)
@@ -159,11 +159,13 @@ ENDIF( cppad_has_ipopt )
 CONFIGURE_FILE(
     ${CMAKE_CURRENT_SOURCE_DIR}/cppad.pc.in
     ${CMAKE_CURRENT_BINARY_DIR}/cppad.pc
+    @ONLY
 )
 # cppad-uninstalled.pc
 CONFIGURE_FILE(
     ${CMAKE_CURRENT_SOURCE_DIR}/cppad-uninstalled.pc.in
     ${CMAKE_CURRENT_BINARY_DIR}/cppad-uninstalled.pc
+    @ONLY
 )
 # During install copy cppad.pc to datadir
 INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/cppad.pc
diff --git a/pkgconfig/cppad-uninstalled.pc.in b/pkgconfig/cppad-uninstalled.pc.in
index 8f3233d0f..7afb73df6 100644
--- a/pkgconfig/cppad-uninstalled.pc.in
+++ b/pkgconfig/cppad-uninstalled.pc.in
@@ -14,7 +14,7 @@
 # includedir=@cppad_SOURCE_DIR@/include
 #
 prefix=@cppad_prefix@
-exec_prefix=$(prefix)
+exec_prefix=${prefix}
 includedir=@cppad_SOURCE_DIR@/include
 libdir=${exec_prefix}/@cppad_libdir@
 #
@@ -24,7 +24,7 @@ Version:               @cppad_version@
 URL:                   @cppad_url@
 #
 Cflags:                -I${includedir}
-Libs:                  -L{libdir} -l@cppad_lib_list@
+Libs:                  -L${libdir} -l@cppad_lib_list@
 Requires:
 Libs.private           @cppad_libs_private@
 Requires.private:      @cppad_requires_private@
diff --git a/pkgconfig/cppad.pc.in b/pkgconfig/cppad.pc.in
index a0c03145b..e6233370d 100644
--- a/pkgconfig/cppad.pc.in
+++ b/pkgconfig/cppad.pc.in
@@ -15,7 +15,7 @@
 # for the meaning of these variables.
 #
 prefix=@cppad_prefix@
-exec_prefix=$(prefix)
+exec_prefix=${prefix}
 includedir=${prefix}/@cppad_includedir@
 libdir=${exec_prefix}/@cppad_libdir@
 #
@@ -28,7 +28,7 @@ Version:               @cppad_version@
 URL:                   @cppad_url@
 #
 Cflags:                -I${includedir}
-Libs:                  -L{libdir} -l@cppad_lib_list@
+Libs:                  -L${libdir} -l@cppad_lib_list@
 Requires:
 Libs.private           @cppad_libs_private@
 Requires.private:      @cppad_requires_private@
```

**Comment by GiulioRomualdi** [comment]
Closing in favor of  the #95

**Pull request closed without merging**
