### PR TITLE
Move the CPPAD_LIB_EXPORT decorator from function definition to function declaration

### LINKED ISSUE #60: Unable to compile CppAD with VisualStudio2019
Hi all. I'm trying to compile this library on Windows using `VisualStudio2019` + `CMake` .

The project is generated without any error. However, when I compile the code on `VisualStudio` I obtain the following errors
```
1>------ Build started: Project: cppad_lib, Configuration: RelWithDebInfo x64 ------
1>cppad_colpack.cpp
1>C:\Users\gromualdi\robot-code\CppAD\cppad_lib\cppad_colpack.cpp(21,5): error C2491: 'CppAD::local::this_routine_should_never_get_called': definition of dllimport function not allowed
1>json_parser.cpp
1>C:\Users\gromualdi\robot-code\CppAD\cppad_lib\json_parser.cpp(23,44): error C2375: 'CppAD::local::graph::json_parser': redefinition; different linkage
1>C:\Users\gromualdi\robot-code\CppAD\include\cppad/local/graph/json_parser.hpp(45): message : see declaration of 'CppAD::local::graph::json_parser'
1>C:\Users\gromualdi\robot-code\CppAD\cppad_lib\json_parser.cpp(26,1): error C2491: 'CppAD::local::graph::json_parser': definition of dllimport function not allowed
1>json_writer.cpp
1>C:\Users\gromualdi\robot-code\CppAD\cppad_lib\json_writer.cpp(20,44): error C2375: 'CppAD::local::graph::json_writer': redefinition; different linkage
1>C:\Users\gromualdi\robot-code\CppAD\include\cppad/local/graph/json_writer.hpp(44): message : see declaration of 'CppAD::local::graph::json_writer'
1>C:\Users\gromualdi\robot-code\CppAD\cppad_lib\json_writer.cpp(23,1): error C2491: 'CppAD::local::graph::json_writer': definition of dllimport function not allowed
1>Generating Code...
1>Done building project "cppad_lib.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========
```
The error is given by the usage of the `maco` `CPPAD_LIB_EXPORT` (alias of `__declspec(dllimport)`). Indeed as written in the [Microsoft documentation](https://docs.microsoft.com/en-us/troubleshoot/cpp/c2491-define-data-member-dllimport), `__declspec(dllimport)` keyword cannot be applied to implement a function. The issue can be easily solved by moving the keyword to the declaration of the function. 

For instance this patch solves the problem (in mine configuration). If you want I can open a PR, however the problem cannot be considered solved by this `patch`. Indeed  unexplored `preprocessor if branches` may have the similar problem. 
See for instance: 
https://github.com/coin-or/CppAD/blob/650e5df8b2a9bf9195f487eb832de7d0e3a06f2d/cppad_lib/cppad_colpack.cpp#L55
```patch
diff --git a/cppad_lib/cppad_colpack.cpp b/cppad_lib/cppad_colpack.cpp
index dc3327053..c815275f4 100644
--- a/cppad_lib/cppad_colpack.cpp
+++ b/cppad_lib/cppad_colpack.cpp
@@ -17,7 +17,9 @@ in the Eclipse Public License, Version 2.0 are satisfied:
 
 # if CPPAD_HAS_COLPACK == 0
 namespace CppAD { namespace local {
-    CPPAD_LIB_EXPORT void this_routine_should_never_get_called(void)
+    CPPAD_LIB_EXPORT void this_routine_should_never_get_called(void);
+
+    void this_routine_should_never_get_called(void)
     {   CPPAD_ASSERT_UNKNOWN(false); }
 } }
 # else // CPPAD_HAS_COLPACK
diff --git a/cppad_lib/json_parser.cpp b/cppad_lib/json_parser.cpp
index fac417d9f..ac0910cee 100644
--- a/cppad_lib/json_parser.cpp
+++ b/cppad_lib/json_parser.cpp
@@ -20,7 +20,7 @@ in the Eclipse Public License, Version 2.0 are satisfied:
 // documentation for this routine is in the file below
 # include <cppad/local/graph/json_parser.hpp>
 
-CPPAD_LIB_EXPORT void CppAD::local::graph::json_parser(
+void CppAD::local::graph::json_parser(
     const std::string& json      ,
     cpp_graph&         graph_obj )
 {   using std::string;
diff --git a/cppad_lib/json_writer.cpp b/cppad_lib/json_writer.cpp
index 250345c6e..add4b20a9 100644
--- a/cppad_lib/json_writer.cpp
+++ b/cppad_lib/json_writer.cpp
@@ -17,7 +17,7 @@ in the Eclipse Public License, Version 2.0 are satisfied:
 // documentation for this routine is in the file below
 # include <cppad/local/graph/json_writer.hpp>
 
-CPPAD_LIB_EXPORT void CppAD::local::graph::json_writer(
+void CppAD::local::graph::json_writer(
     std::string&                              json                   ,
     const cpp_graph&                          graph_obj              )
 {   using std::string;
diff --git a/include/cppad/local/graph/json_parser.hpp b/include/cppad/local/graph/json_parser.hpp
index 17bcc7c7e..a28d2c045 100644
--- a/include/cppad/local/graph/json_parser.hpp
+++ b/include/cppad/local/graph/json_parser.hpp
@@ -42,7 +42,7 @@ Upon return it is a $cref cpp_ad_graph$$ representation of this function.
 $head Prototype$$
 $srccode%hpp% */
 namespace CppAD { namespace local { namespace graph {
-    void json_parser(
+    CPPAD_LIB_EXPORT void json_parser(
         const std::string&  json      ,
         cpp_graph&          graph_obj
     );
diff --git a/include/cppad/local/graph/json_writer.hpp b/include/cppad/local/graph/json_writer.hpp
index 36a4cb39f..299c56cc0 100644
--- a/include/cppad/local/graph/json_writer.hpp
+++ b/include/cppad/local/graph/json_writer.hpp
@@ -41,7 +41,7 @@ This is a $code cpp_graph$$ object.
 $head Prototype$$
 $srccode%hpp% */
 namespace CppAD { namespace local { namespace graph {
-    void json_writer(
+    CPPAD_LIB_EXPORT void json_writer(
         std::string&       json        ,
         const cpp_graph&   graph_obj
     );
```

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR fixes #60 

cc @traversaro @s-dafarra

### CODE REVIEW

**Comment by bradbell** [comment]
As I understand the code in define.hpp, if one is compiling on windows they should add 
```
-D cppad_lib_EXPORTS=YES
```
to the cmake command line. Is this what you are doing ?

Also, I think that the CPPAD_LIB_EXPORT marco is also needed for the functions in the following include files:

1. cppad/example/code_gen_fun.hpp:
2. cppad/local/graph/cpp_graph_op.hpp:
3. cppad/local/graph/json_lexer.hpp:

Does this seem correct to you ?

**Comment by traversaro** [comment]
> to the cmake command line. Is this what you are doing ?

No, the `cppad_lib_EXPORTS` is automatically defined by CMake if the `cppad_lib` target is compiled as a shared library, see https://cmake.org/cmake/help/latest/prop_tgt/DEFINE_SYMBOL.html .

**Comment by bradbell** [comment]
In that case, it does not need to be discussed in the CppAD the cmake documentation
file:///home/bradbell/repo/cppad.git/doc/cmake.htm
because it is automatic. Thanks.

**Comment by traversaro** [comment]
Exactly.

**Comment by bradbell** [comment]
I must have done something wrong. I am testing the current version using the instructions under Visual Studio on

**Comment by traversaro** [comment]
`cppad_lib.lib`  was compiled as static library. Looking into https://github.com/coin-or/CppAD/blob/master/cppad_lib/CMakeLists.txt#L52, it seems so. In that case, it seems that the code in https://github.com/coin-or/CppAD/blob/79e1cfdc1f13fc61fdfd90c28936affe68abcade/include/cppad/local/define.hpp#L60 is not completely correct, as if the library was not compiled as shared, then `CPPAD_LIB_EXPORT`  should be defined as empty and not as `__declspec(dllimport)` . 
This is the reason why https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html is tipically used to generate those headers, to generate different code depending on the type of library that is compiled (if shared or static).
However, if you only support CMake on Windows, a relatively easy fix is to modify the snippet of code as:
~~~
# if defined(_MSC_VER) && defined(cppad_lib_STATIC)
# ifdef  cppad_lib_EXPORTS
# define CPPAD_LIB_EXPORT __declspec(dllexport)
# else
# define CPPAD_LIB_EXPORT __declspec(dllimport)
# endif  // cppad_lib_EXPORTS
# else   // _MSC_VER
# define CPPAD_LIB_EXPORT
# endif
~~~

and then in CMake add: 
~~~
get_target_property(cppad_lib_target_type cppad_lib TYPE)
if(cppad_lib_target_type STREQUAL "STATIC_LIBRARY")
  target_compile_definitions(cppad_lib PUBLIC cppad_lib_STATIC)
endif()
~~~

**Comment by traversaro** [comment]
Sorry for not noticing this before.

**Comment by traversaro** [comment]
An alternative to support shared libraries on Windows without manually managing the visibility with `CPPAD_LIB_EXPORT` is simply to use the [`CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`](https://blog.kitware.com/create-dlls-on-windows-without-declspec-using-new-cmake-export-all-feature/), that support compilation as a shared library exporting all symbols (expect for static variables).

**Comment by bradbell** [comment]
Thanks !! 
I think this is confused by the fact that I was using static libraries for WIndows (when I could not get the dynamic onse to work). See the following code from cppad_lib/CMakeLists.txt:
```
IF( ${CMAKE_SYSTEM_NAME} STREQUAL "Windows" )
    MESSAGE( STATUS "Windows system so building static cppad_lib")
    ADD_LIBRARY( cppad_lib STATIC ${source_list} )
ELSE( ${CMAKE_SYSTEM_NAME} STREQUAL "Windows" )
    MESSAGE( STATUS "Not Windows system so building shared cppad_lib")
    ADD_LIBRARY( cppad_lib SHARED ${source_list} )
    SET_TARGET_PROPERTIES( cppad_lib PROPERTIES SOVERSION ${soversion} )
    #
    FIND_LIBRARY(dl_LIBRARY dl)
    IF( dl_LIBRARY )
        TARGET_LINK_LIBRARIES(cppad_lib ${dl_LIBRARY})
    ENDIF( dl_LIBRARY )
ENDIF( ${CMAKE_SYSTEM_NAME} STREQUAL "Windows" )
```

In fact, my cmake output has `-- Windows system so building static cppad_lib`

**Comment by traversaro** [comment]
Yes, for how the CMake is now, it is only possible to compile static libraries on Windows.

**Comment by bradbell** [comment]
I changed cppad_lib/CMakeLists.txt to build shared libraries on windows and fixed a few more problems that came up during `nmake check`; see https://github.com/coin-or/CppAD/commit/92c9946d090a0ad90a8ca7a5c194a9e9c684127a.

Now I am stuck on the following error during the `nmake check` command:
```
[ 33%] Linking CXX executable example_graph.exe
[ 33%] Built target example_graph
Scanning dependencies of target check_example_graph
NMAKE : fatal error U1077: '.\example_graph.exe' : return code '0xc0000135'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\nmake.exe"' : return code '0x2'
```

**Comment by bradbell** [comment]
I think I figured it out. One needs to add the directory where the library was built to the system path.
I did this and the build went past that error but stopped at another point that has nothing to do with the dll.

**Comment by traversaro** [comment]
> 
> 
> I think I figured it out. One needs to add the directory where the library was built to the system path.
> I did this and the build went past that error but stopped at another point that has nothing to do with the dll.

A common strategy for that is to set:
~~~
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
~~~
so that all the .exe and .dll during build go in `build/bin` , and so they are in the same directory automatically, without needing to tweak the system path.  See  https://github.com/robotology/how-to-export-cpp-library/blob/master/CMakeLists.txt#L41 for reference.

**Comment by bradbell** [comment]
Given the results of my testing, it seems to me that a static variable in a C++ template function can different values in the DLL than in the rest of the code for a program. Is this true ?

**Comment by traversaro** [comment]
> 
> 
> Given the results of my testing, it seems to me that a static variable in a C++ template function can different values in the DLL than in the rest of the code for a program. Is this true ?

I am not sure what you mean by "can different values" ?

**Comment by bradbell** [comment]
Suppose I have a template function:
```
template <class Type>
Type  count_calls(void)
{   static Type count_ = Type(0);
    return( ++count_ );
}
```
On unix, there would be one counter for calls to `count_calls` both inside and outside the shared library. It seems to me there would be two counters, one for calls inside the DLL and one for calls outside the DLL on windows ?

**Comment by bradbell** [comment]
I have reverted back to building a static version of the library when using windows; see the heading Visual Studio on
file:///home/bradbell/repo/cppad.git/doc/cmake.htm#CMake%20Command.Visual%20Studio

If someone wants to try and  make the shared version work; they will need to re-enable the definition of CPPAD_LIB_EXPORT in define.hpp and CMakeLists.tst; see the changes to CMakeLists.txt and define.hpp on.
https://github.com/coin-or/CppAD/commit/d4780b64580099f57220d1dec17410078b3c3d16

I am got int start a discussion about this topic.

**Comment by Wang-Peng-debug** [comment]
Does anyone find the way of How to build a DLL file for CppAD on Windows? I saw you guys started a discussion for this but still found no ways of that, please tell me how if anyone knows this, which would be of much help for me and I would appreciated it so much!!!!!!!!!!!!!!!

**Pull request merged**
