### PR TITLE
Add uninstall target

### PR DESCRIPTION
**Pull request by jcarpent**
To simply perform `make uninstall` when it is needed.

### CODE REVIEW

**Comment by bradbell** [comment]
Thanks for the suggestion. 

1. Do you think we should remove directories that are empty after the files are removed ?

2. Given your solution, I checked on the web an found this:
https://gitlab.kitware.com/cmake/community/wikis/FAQ#can-i-do-make-uninstall-with-cmake
Do you like your solution better ?

3. If we do include your solution as is, what should I put for a copyright message at the top of th
cppad_uninstall.cmake ?

**Comment by jcarpent** [comment]
> Thanks for the suggestion.

It is a pleasure.

>     1. Do you think we should remove directories that are empty after the files are removed ?

This is not a common strategy as far as I know. I would say we should let them empty as it might be used by others libs, such cppadcodegen for instance.

>     2. Given your solution, I checked on the web an found this:
>        https://gitlab.kitware.com/cmake/community/wikis/FAQ#can-i-do-make-uninstall-with-cmake
>        Do you like your solution better ?

Their solution seems very specific to LINUX system, with the `$ENV{DESTDIR}` use. So the solution I suggest is then very similar, except it seems to be more generic.

>     3. If we do include your solution as is, what should I put for a copyright message at the top of th
>        cppad_uninstall.cmake ?

This file may be present in various locations, such as https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/cmake_uninstall.cmake.in, inside the cmake module that I'm co-developing, or also inside the Eigen project. The solution I took is coming from Eigen, which I find minimalist and it works well. So, we can rely on their license. @bradbell Do you want me to add it?

**Comment by jcarpent** [comment]
@bradbell I've also changed the CI to test the install and uninstall targets

**Comment by bradbell** [comment]
1. I have not yet added this to the API, i.e., added the uninstall instructions in
https://coin-or.github.io/CppAD/doc/install.htm

2. I would be nice if we could change the alternative license to be GPL-2 so it was the same as the rest of CppAD; see
https://github.com/coin-or/CppAD/blob/master/cmake/cppad_uninstall.cmake

**Pull request merged**
